name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
     
  build-windows:
    name: Windows
    runs-on: windows
    steps:
      - run: |
         make build

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows Artifacts
          path: build/release/*.exe   
  
        

        
        
          
          
