on: [push, pull_request]
name: Build and Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        path: tmp/artifact
    - uses: actions/checkout@v3

    - name: Build
      run: |
        make build
    
    - name: Upload to Artifacts
      uses: actions/checkout@v3
      with:
         name: Windows Artifacts
         path: build/
  
        

        
        
          
          
