on: [push, pull_request]
name: Build and Test
jobs:
     
  build-windows:
    name: Windows
    runs-on: windows
   
    defaults:
      run:
        shell: bash
    steps:
      - run: make build

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows Artifacts
          path: build/release/*.exe   
  
        

        
        
          
          
